version: '3.3'
services:
  nginx-reverse-proxy:
    image: jwilder/nginx-proxy:1.6.4
    container_name: nginx-reverse-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./no_limit.conf:/etc/nginx/conf.d/my_proxy.conf:ro
    environment:
      - DEFAULT_HOST=api-intra.cuisinesetfourneaux.com
    networks:
      - nginx-proxy
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh
      # d5bc3f43be991424
      # 2a8735afeb616fc7567550379d3ba3db
    environment:
      - NGINX_PROXY_CONTAINER=nginx-reverse-proxy
      # - ACME_CHALLENGE=DNS-01
      # - ACMESH_DNS_API_CONFIG={'DNS_API': 'dns_cf', 'CF_Key': 'd5bc3f43be991424', 'CF_Email': 'yourCloudflareAccountEmail'}
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true