#version: '3.8'

services:
  food-front:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      PORT: 2800
    ports:
      - "2800:2800"  # Expose le port 2800 de votre machine hôte vers le conteneur
    restart: always
