#version: '3.8'

services:
  food-front:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      PORT: 2800
      VIRTUAL_PORT: 2800
      VIRTUAL_HOST: food.paolo-sportelli.fr  # Assurez-vous de remplacer par votre domaine
      LETSENCRYPT_HOST: food.paolo-sportelli.fr  # Assurez-vous de remplacer par votre domaine
      LETSENCRYPT_EMAIL: paolo110101@yahoo.fr
    networks:
      - nginx-proxy
    restart: always

networks:
  nginx-proxy:
    external: true