version: '3.8'

services:
  destockdis-front:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      PORT: 2800
      VIRTUAL_PORT: 2800
      VIRTUAL_HOST: stock.destockdis.com  # Assurez-vous de remplacer par votre domaine
      LETSENCRYPT_HOST: stock.destockdis.com  # Assurez-vous de remplacer par votre domaine
      LETSENCRYPT_EMAIL: camille@cuisinesetfourneaux.com
    networks:
      - nginx-proxy
    restart: always

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #     - "8081:8081"
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d
  #     - /etc/letsencrypt:/etc/letsencrypt:ro
  #   depends_on:
  #     - app
  #   networks:
  #     - my_network
  #   restart: always
networks:
  nginx-proxy:
    external: true
  # Ajoutez d'autres services ici si nécessaire (comme une base de données, etc.)
